[2023-10-14T13:19:35.614+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.gcs_to_big_query manual__2023-10-14T13:19:31.370565+00:00 [queued]>
[2023-10-14T13:19:35.619+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.gcs_to_big_query manual__2023-10-14T13:19:31.370565+00:00 [queued]>
[2023-10-14T13:19:35.619+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T13:19:35.620+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-14T13:19:35.620+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T13:19:35.627+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_big_query> on 2023-10-14 13:19:31.370565+00:00
[2023-10-14T13:19:35.631+0000] {standard_task_runner.py:55} INFO - Started process 4954 to run task
[2023-10-14T13:19:35.634+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigquery_data_load', 'gcs_to_big_query', 'manual__2023-10-14T13:19:31.370565+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_data_load.py', '--cfg-path', '/tmp/tmpxm_vyd4k']
[2023-10-14T13:19:35.635+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask gcs_to_big_query
[2023-10-14T13:19:35.669+0000] {task_command.py:388} INFO - Running <TaskInstance: bigquery_data_load.gcs_to_big_query manual__2023-10-14T13:19:31.370565+00:00 [running]> on host 4c2fe63b7c62
[2023-10-14T13:19:35.706+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Niko
AIRFLOW_CTX_DAG_ID=bigquery_data_load
AIRFLOW_CTX_TASK_ID=gcs_to_big_query
AIRFLOW_CTX_EXECUTION_DATE=2023-10-14T13:19:31.370565+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-14T13:19:31.370565+00:00
[2023-10-14T13:19:35.707+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-14T13:19:35.707+0000] {gcs_to_bigquery.py:377} INFO - Using existing BigQuery table for storing data...
[2023-10-14T13:19:35.708+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2023-10-14T13:19:35.709+0000] {bigquery.py:2260} INFO - Project is not included in destination_project_dataset_table: vehicle_analytics.history; using project "***-400718"
[2023-10-14T13:19:35.710+0000] {gcs_to_bigquery.py:381} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': '***-400718', 'datasetId': 'vehicle_analytics', 'tableId': 'history'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://n1-logistics-landing-bucket/*'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-14T13:19:35.710+0000] {bigquery.py:1542} INFO - Inserting job ***_bigquery_data_load_gcs_to_big_query_2023_10_14T13_19_31_370565_00_00_61a69820898a82270818149ec12e8762
[2023-10-14T13:19:36.581+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 440, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Uris gs://n1-logistics-landing-bucket/*
[2023-10-14T13:19:36.593+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigquery_data_load, task_id=gcs_to_big_query, execution_date=20231014T131931, start_date=20231014T131935, end_date=20231014T131936
[2023-10-14T13:19:36.607+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 58 for task gcs_to_big_query (404 Not found: Uris gs://n1-logistics-landing-bucket/*; 4954)
[2023-10-14T13:19:36.647+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-10-14T13:19:36.664+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
